### ISSUE TITLE
关于lua插件功能

### ISSUE THREAD

**Issue by chenxuuu** [UudrSgMEZ/V2RayGCon#2]
直接丢到`lua/modules`就行了嘛？开启软件自动运行？

**Comment by UudrSgMEZ** [comment]
不是，那里面只是放了几个常用的功能模块。

要使用lua功能首先要在`选项`-`插件`里面钩上`Luna`后面的`使用`，然后`保存`。
这时托盘图标的右键菜单里面会多出个“插件”菜单项。
点开`luna`插件里面有编辑，测试等功能。

Luna插件里面钩了`自启动`的脚本运行时会把输出信息打印在日志窗口。
启动顺序是 `V2RayGCon`->`Luna插件`->`你的脚本`。

`lua/modules`目录里面放的模块，可以像下面那样调用。
```lua
节选自lua/Example.lua
-----------------------
local Logger = require "lua.modules.logger"
local logger = Logger(testLogFileName)
logger:Info("Hello")
```
也可以新建个文件夹来放自己写的共用模块。

**Comment by chenxuuu** [comment]
ok，能跑起来
Signal、Json、Misc、Server、Web这几个库功能基本都挺全了
