### ISSUE TITLE
a bug of subscription

### ISSUE THREAD

**Issue by evilkong** [UudrSgMEZ/V2RayGCon#3]
最近多了一个环境，使用订阅的时候，发现总提示订阅解析失败，复制具体内容对比后发现，最后那里少了个符号"}"

复制出来的解析失败内容: ...idGxzIjogIiIK

对比订阅地址的内容: ...idGxzIjogIiIKfQ

烦请大大跟踪修复，谢谢

**Comment by UudrSgMEZ** [comment]
[V2RayGCon v1.1.13.3](https://github.com/UudrSgMEZ/V2RayGCon/releases/tag/1.1.13.3)

**Comment by evilkong** [comment]
pass. Thanks.
