### ISSUE TITLE
非正常中止问题

### ISSUE THREAD

**Issue by Erven2016** [UudrSgMEZ/V2RayGCon#7]
[高级 国内 中继x...] V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom

开发者，你好：

希望您能够帮我解决这个问题，以下是服务器日志

[高级 国内 中继x...] A unified platform for anti-censorship.
[高级 国内 中继x...] main: failed to read config file: stdin: > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: Failed to build TCP config. > v2ray.com/core/infra/conf: invalid TCP header config > v2ray.com/core/infra/conf: unknown config id: chacha20-poly1305
[高级 国内 中继x...] 
[高级 国内 中继x...]  > exit status -1
[高级 国内 中继x...] v2ray-core 已关闭!

chahca20-poly1305这个加密方式是有问题的？

**Comment by UudrSgMEZ** [comment]
"invalid TCP header config"看来是导入vmess链接时生成的配置不对导致服务器无法启动。这有可能是因为vmess分享链接没按[v2rayN的vmess标准](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))来生成，也有可能是V2RayGCon在解析vmess的时候出bug了。需要你提供一下原来的vmess分享链接才可以分析具体问题出在哪。

如果配置是你自己填写的，那么需要提供下完整的配置来分析。

注意给服务器信息打下码，不然别人就可以用你的服务器了。

**Comment by Erven2016** [comment]
使用的是机场的订阅链接，Android的v2rayN正常

不麻烦的话可以telegram联系我，方便分享vmess链接

telegram: t.me/erven2016

或邮箱 leiguihua2016@gmail.com

**Comment by Erven2016** [comment]
不好意思没有仔细读README.MD，才发现不能问联系方式，我这里自己看一下吧配置文件吧

**Comment by UudrSgMEZ** [comment]
你可以把像下面这样的订阅内容：
dm1lc3M6Ly9leUp3Y3lJNklteHZkbVZzZVNJc0ltRmtaQ0k2SWpFdU1pNHpMalFpTENKd2IzSjBJam9pTVRJek5DSXNJbWxrSWpvaVlUWTNNakZsWVdFdE0yTXlOQzAwWWpkbExXRXlNRE10T0RBMVptVmpZelpoTTJSbElpd2lZV2xrSWpvaU1DSXNJbTVsZENJNkluZHpJaXdpZEhsd1pTSTZJaUlzSW1odmMzUWlPaUlpTENKMGJITWlPaUowYkhNaUxDSjJJam9pTWlJc0luQmhkR2dpT2lJdmRqSnlZWGtpZlE9PQ0K

base64解码一次（有很多在线解码网站的）,得出像下面这样的vmess链接：
vmess://eyJwcyI6ImxvdmVseSIsImFkZCI6IjEuMi4zLjQiLCJwb3J0IjoiMTIzNCIsImlkIjoiYTY3MjFlYWEtM2MyNC00YjdlLWEyMDMtODA1ZmVjYzZhM2RlIiwiYWlkIjoiMCIsIm5ldCI6IndzIiwidHlwZSI6IiIsImhvc3QiOiIiLCJ0bHMiOiJ0bHMiLCJ2IjoiMiIsInBhdGgiOiIvdjJyYXkifQ==

再把vmess链接的内容base64解码一次就得出明文了：
{"ps":"lovely","add":"1.2.3.4","port":"1234","id":"a6721eaa-3c24-4b7e-a203-805fecc6a3de","aid":"0","net":"ws","type":"","host":"","tls":"tls","v":"2","path":"/v2ray"}

然后就可以去掉服务器相关信息了。

**Comment by Erven2016** [comment]
{"ps":"高级 国内 中继x1 香港 A","add":"已删除","port":"已删除","id":"58d1ffef-0024-cd89-7d9f-959ca085005a","aid":"2","net":"tcp","type":"chacha20-poly1305","host":"","tls":"none","v":"2","path":""}

**Comment by UudrSgMEZ** [comment]
这个问题和Qv2ray的[issue #109](https://github.com/lhy0403/Qv2ray/issues/109)相同。

新发布的[v1.2.5.4](https://github.com/UudrSgMEZ/V2RayGCon/releases/tag/1.2.5.4)修复了vmess解析问题，但是这个软件没有像v2rayN那样的全局tcp伪装设置，所以不确定是否能连上服务器。

**Comment by Erven2016** [comment]
好的，谢谢，晚上回来再试，谢谢开发者
